name: Raging Death Films
markdown: redcarpet
pygments: false
paginate: 10

#Your site basic configuration
baseurl: /
permalinks: pretty

#Your site custom configuration (used in layout)

#Exluce unrelated files
exclude:
- README.md

# Prose specific config
prose:
  #Entry point used on http://prose.io/
  rooturl: '_posts'
  #Your site url
  siteurl: 'http://rdf.github.io/'
  
  #relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  #Default media folder for uploaded content on prose.io
  media: 'media'

